import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import crypto from 'node:crypto';
import path from 'node:path';
import {Store,ConflictError} from '../web/store.mjs';
import {importVault} from '../web/import.mjs';
import {restoreBackup} from '../web/backup.mjs';
const temp=t=>{const p=fs.mkdtempSync(path.join(os.tmpdir(),'stamp-store-'));t.after(()=>fs.rmSync(p,{recursive:true,force:true}));return p};
const record={key:'Places/Example',kind:'Places',body:'Original prose',data:{title:'Example',custom:{keep:true},stamps:[{id:'main',name:'Main',type:'main',extra:1}],visits:[{id:'visit-one',date:'2025-01-01',trip:'[[Trips/Roadtrip]]',notes:'Hello',stamps:[{id:'ink-one',name:'Main',type:'main',photos:['[[Attachments/a.png]]'],extra:'saved'}]}],stamping_locations:[{id:'desk',name:'Front desk',reports:[{id:'report',origin:'authored',custom:'preserved'}]}]}};
test('SQLite reconstructs normalized records losslessly and persists across reopen',t=>{const dir=temp(t);let store=new Store(dir);const created=store.create(record);assert.deepEqual(created.data,record.data);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM impressions').get().n,1);store.close();store=new Store(dir);assert.deepEqual(store.get(record.key),created);assert.equal(store.list().length,1);store.close()});
test('optimistic revisions reject stale writes and restore appends a revision',t=>{const store=new Store(temp(t));t.after(()=>store.close());store.create(record);const changed=store.save(record.key,{body:'New',prose:{about:{json:{type:'doc'},html:'<p>New</p>'}}},{expectedRevision:1,actor:'Alex',summary:'Update'});assert.equal(changed.revision,2);assert.throws(()=>store.save(record.key,{body:'lost'},{expectedRevision:1}),e=>e instanceof ConflictError&&e.current.body==='New');assert.equal(store.history(record.key).length,2);assert.throws(()=>store.restore(record.key,1,{expectedRevision:1}),ConflictError);const restored=store.restore(record.key,1,{expectedRevision:2});assert.equal(restored.body,'Original prose');assert.equal(restored.prose,undefined);assert.equal(restored.revision,3);assert.equal(store.revision(record.key,2).body,'New');assert.throws(()=>store.db.exec('DELETE FROM revisions'),/append-only/)});
test('failed normalized write rolls back all tables and history',t=>{const store=new Store(temp(t));t.after(()=>store.close());store.create(record);assert.throws(()=>store.save(record.key,{data:{...record.data,visits:[null]}},{expectedRevision:1}));assert.deepEqual(store.get(record.key).data,record.data);assert.equal(store.history(record.key).length,1)});
test('backup and restore retain database revisions and uploaded bytes',t=>{const dir=temp(t),store=new Store(path.join(dir,'live'));store.create(record);fs.writeFileSync(path.join(store.uploadsDir,'a.png'),'photo');store.registerAsset({path:'a.png',mime:'image/png',size:5,sha256:crypto.createHash('sha256').update('photo').digest('hex')});store.backup(path.join(dir,'backup'));store.close();restoreBackup({from:path.join(dir,'backup'),dataDir:path.join(dir,'restored')});const restored=new Store(path.join(dir,'restored'));assert.deepEqual(restored.get(record.key).data,record.data);assert.equal(restored.history(record.key).length,1);assert.equal(fs.readFileSync(path.join(restored.uploadsDir,'a.png'),'utf8'),'photo');assert.equal(restored.getAsset('a.png').size,5);restored.close();assert.throws(()=>restoreBackup({from:path.join(dir,'backup'),dataDir:path.join(dir,'restored')}),/absent or empty/)});
test('repeat import is idempotent and cannot overwrite edited data',t=>{const dir=temp(t),dataDir=path.join(dir,'data');const result=importVault({vault:path.resolve('vault'),dataDir});assert.ok(result.count>400);let store=new Store(dataDir);const first=store.list().find(n=>n.kind==='Places');store.save(first.key,{body:'Browser-authored'},{expectedRevision:1});store.close();assert.equal(importVault({vault:path.resolve('vault'),dataDir}).idempotent,true);store=new Store(dataDir);assert.equal(store.get(first.key).body,'Browser-authored');store.close()});
test('separate connections cannot overwrite a revision unknowingly',t=>{const dir=temp(t),a=new Store(dir),b=new Store(dir);t.after(()=>{a.close();b.close()});a.create(record);const opened=b.get(record.key);a.save(record.key,{body:'From another connection'},{expectedRevision:1});assert.throws(()=>b.save(record.key,{body:'Stale tab'},{expectedRevision:opened.revision}),e=>e.status===409&&e.current.revision===2);assert.equal(b.get(record.key).body,'From another connection')});
test('invalid import validates before creating a database',t=>{const dir=temp(t),vault=path.join(dir,'vault'),dataDir=path.join(dir,'data');fs.mkdirSync(path.join(vault,'Places'),{recursive:true});fs.writeFileSync(path.join(vault,'Places/Broken.md'),'---\ntitle: Missing required fields\n---\n');assert.throws(()=>importVault({vault,dataDir}));assert.equal(fs.existsSync(dataDir),false)});
test('changed source refuses to replace imported edits',t=>{const dir=temp(t),vault=path.join(dir,'vault'),dataDir=path.join(dir,'data');for(const kind of ['Places','Trips','Regions'])fs.cpSync(path.resolve('vault',kind),path.join(vault,kind),{recursive:true});importVault({vault,dataDir});const file=path.join(vault,'Places',fs.readdirSync(path.join(vault,'Places'))[0]);fs.appendFileSync(file,'\nChanged source text.\n');assert.throws(()=>importVault({vault,dataDir}),/not empty/)});
test('populated QA import preserves every raw field and complete rendered pages', {skip:!fs.existsSync('.qa/vault')}, async t=>{
 const {loadContent,loadRecords,parseNote,walk}=await import('../src/content.mjs');const {createSite}=await import('../src/site.mjs');
 const vault=path.resolve('.qa/vault'),dataDir=path.join(temp(t),'data'),result=importVault({vault,dataDir});assert.ok(result.assets>0);
 let store=new Store(dataDir);store.close();store=new Store(dataDir);t.after(()=>store.close());
 for(const kind of ['Places','Trips','Regions'])for(const file of walk(path.join(vault,kind)).filter(f=>f.endsWith('.md'))){const key=path.relative(vault,file).slice(0,-3).replaceAll(path.sep,'/'),raw=parseNote(fs.readFileSync(file,'utf8'));assert.deepEqual(store.get(key).data,raw.data,key);assert.equal(store.get(key).body,raw.body,key)}
 const fromFiles=loadContent(vault),fromDB=loadRecords(store.list(),{assets:store.listAssets().map(a=>({path:a.path,file:path.join(store.uploadsDir,a.path)}))}),catalogue=JSON.parse(fs.readFileSync('data/catalogue.json','utf8'));
 const oldSite=createSite(fromFiles,catalogue,'test'),newSite=createSite(fromDB,catalogue,'test');assert.deepEqual([...newSite.pages.keys()].sort(),[...oldSite.pages.keys()].sort());for(const [url,html] of oldSite.pages)assert.equal(newSite.pages.get(url),html,url);assert.deepEqual(newSite.search.toSorted((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),oldSite.search.toSorted((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))));
});
