import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import YAML from 'yaml';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {slug} from '../src/content.mjs';
const out=path.resolve('.qa/screenshots');fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch(process.env.QA_CHROME==='1'?{channel:'chrome'}:{});
const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const base=process.env.QA_URL||'http://localhost:8767',realBase=process.env.QA_REAL_URL||'http://localhost:8766';const results=[];
const record=(name,data={})=>results.push({name,...data});
const go=async slug=>{await page.goto(`${base}/places/${slug}/`);await page.locator('h1').waitFor()};
const noOverflow=async()=>{const v=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert.ok(v.scroll<=v.client,JSON.stringify(v));return v};
const axe=async(name)=>{const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();record(name,{violations:a.violations})};
const imageReady=async locator=>{await locator.scrollIntoViewIfNeeded();await locator.evaluate(async image=>{if(!image.complete)await new Promise((resolve,reject)=>{image.addEventListener('load',resolve,{once:true});image.addEventListener('error',reject,{once:true})});if(!image.naturalWidth)throw Error(`Image did not load: ${image.src}`)})};
const expectOpen=async selector=>{await page.locator(`${selector}[open]`).waitFor({state:'attached'});assert.equal(await page.locator(selector).getAttribute('open'),'')};
const expectedStatePlaces=state=>fs.readdirSync('.qa/vault/Places').filter(file=>file.endsWith('.md')).filter(file=>{const source=fs.readFileSync(path.join('.qa/vault/Places',file),'utf8'),frontmatter=source.match(/^---\r?\n([\s\S]*?)\r?\n---/);return YAML.parse(frontmatter[1]).states.includes(state)}).map(file=>`/places/${slug(file.slice(0,-3))}/`).sort();
const squareGallery=async()=>{
 const sizes=await page.locator('.album-slot>img,.album-slot>.empty-stamp').evaluateAll(slots=>slots.map(slot=>{const r=slot.getBoundingClientRect();return {width:r.width,height:r.height}}));
 assert.ok(sizes.length>0);for(const size of sizes)assert.ok(Math.abs(size.width-size.height)<=1,JSON.stringify(size));
};
const checkAssociations=async()=>{
 assert.equal(await page.locator('#visits').evaluate(section=>section.nextElementSibling?.id),'associations');
 assert.equal(await page.locator('#associations > h2').innerText(),'Associations');
 assert.equal(await page.locator('#associations .prose > p').count(),2);
 assert.match(await page.locator('#associations').innerText(),/The Solace of Open Spaces/);assert.match(await page.locator('#associations').innerText(),/Harvest Moon/);
 assert.doesNotMatch(await page.locator('#notes').innerText(),/The Solace of Open Spaces|Harvest Moon/);
 const link=page.locator('#associations a');assert.equal(await link.count(),1);assert.equal(await link.getAttribute('href'),'https://example.com/book-review');assert.equal(await link.innerText(),'The Solace of Open Spaces');assert.equal(await link.evaluate(anchor=>getComputedStyle(anchor).display),'inline');
 assert.equal(await page.locator('#associations article,#associations button,#associations .card,#associations .pill').count(),0);
};
const albumGeometry=()=>page.locator('.cancellation-summary').evaluate(summary=>{
 const measure=(slot,origin)=>{const rect=slot.getBoundingClientRect();return {width:rect.width,height:rect.height,x:rect.x-origin.x,y:rect.y-origin.y,href:slot.getAttribute('href'),collected:slot.dataset.collected,hasPhoto:slot.dataset.hasPhoto}};
 const primary=summary.querySelector('.primary-cancellation'),primarySlot=primary?.querySelector('.primary-slot'),primaryRect=primary?.getBoundingClientRect();
 const album=summary.querySelector('.secondary-cancellations .cancellation-album'),rect=album?.getBoundingClientRect();
 return {total:Number(summary.dataset.total),primary:primarySlot?{...measure(primarySlot,primaryRect),containerWidth:primaryRect.width}:null,secondary:album?{width:rect.width,height:rect.height,count:Number(album.dataset.count),slots:[...album.querySelectorAll('.cancellation-slot')].map(slot=>measure(slot,rect))}:null};
});
const squareSlots=geometry=>{
 const slots=[geometry.primary,...(geometry.secondary?.slots||[])].filter(Boolean);
 for(const slot of slots){assert.ok(Math.abs(slot.width-slot.height)<=1,JSON.stringify(slot));assert.ok(slot.width>20,JSON.stringify(slot))}
 if(geometry.primary)assert.ok(Math.abs(geometry.primary.width-geometry.primary.containerWidth)<=1,'The primary cancellation fills its panel width');
 for(const slot of geometry.secondary?.slots||[])assert.ok(slot.x>=-1&&slot.y>=-1&&slot.x+slot.width<=geometry.secondary.width+1&&slot.y+slot.height<=geometry.secondary.height+1,JSON.stringify({geometry,slot}));
};
const verifyCountRange=async()=>{
 const footprints=[];
 for(let count=1;count<=10;count++){
  await go(`qa-cancellation-count-${count}`);const geometry=await albumGeometry();assert.equal(geometry.total,count);assert.ok(geometry.primary);assert.equal(geometry.secondary?.count||0,count-1);assert.equal(geometry.secondary?.slots.length||0,count-1);squareSlots(geometry);await noOverflow();
  const slots=[geometry.primary,...(geometry.secondary?.slots||[])];assert.equal(slots.length,count);assert.equal(new Set(slots.map(slot=>slot.href)).size,count);
  assert.equal(slots.filter(s=>s.collected==='true').length,Math.ceil(count/2));assert.equal(slots.filter(s=>s.collected==='false').length,Math.floor(count/2));
  assert.equal(geometry.primary.href,count===1?'#cancellation-record-details':'#cancellation-record-expected-1');assert.equal(await page.locator('.primary-date time').getAttribute('datetime'),'2026-09-20');assert.equal(await page.locator('.date-day').innerText(),'20');
  if(count===3)assert.equal(slots.filter(s=>s.collected==='true'&&s.hasPhoto==='false').length,1);
  footprints.push({count,primaryWidth:geometry.primary.width,primaryHeight:geometry.primary.height,secondary:geometry.secondary?{width:geometry.secondary.width,height:geometry.secondary.height,count:geometry.secondary.count,slot:geometry.secondary.slots[0].width}:null});
  if(count===1){assert.equal(geometry.secondary,null);assert.equal(await page.locator('#cancellation-details').count(),1)}
  if(count===10){const rows=new Set(geometry.secondary.slots.map(s=>Math.round(s.y))),columns=new Set(geometry.secondary.slots.map(s=>Math.round(s.x)));assert.equal(rows.size,3);assert.equal(columns.size,3);assert.equal(await page.locator('.album-more').count(),0);const caption=await page.locator('.map-figure figcaption').innerText();assert.match(caption,/State context/);assert.doesNotMatch(caption,/Park location/)}
 }
 for(const footprint of footprints){assert.ok(Math.abs(footprint.primaryWidth-footprints[0].primaryWidth)<=1,JSON.stringify(footprints));assert.ok(Math.abs(footprint.primaryHeight-footprints[0].primaryHeight)<=1,JSON.stringify(footprints));if(footprint.secondary){assert.ok(Math.abs(footprint.secondary.width-footprints[1].secondary.width)<=1,JSON.stringify(footprints));assert.ok(Math.abs(footprint.secondary.height-footprints[1].secondary.height)<=1,JSON.stringify(footprints))}}
 return footprints;
};
try{
 await go('yellowstone-national-park');
 assert.equal(await page.locator('.visit').count(),2);
 assert.equal(await page.locator('.cancellation-slot').count(),6);
 assert.equal(await page.locator('.cancellation-artwork').count(),6);
 assert.equal(await page.locator('.cancellation-artwork').evaluateAll(images=>new Set(images.map(i=>i.src)).size),6);
 assert.equal(await page.locator('.primary-slot').getAttribute('href'),'#cancellation-record-geyser-main');assert.equal(await page.locator('.primary-date time').getAttribute('datetime'),'2019-06-19');assert.equal(await page.locator('.primary-date time .sr-only').innerText(),'June 19, 2019');assert.equal(await page.locator('.secondary-cancellations .cancellation-slot').count(),5);
 assert.equal(await page.locator('#stamping-locations').evaluate(e=>e.tagName),'DETAILS');
 assert.equal(await page.locator('#stamping-locations').getAttribute('open'),null);
 assert.equal(await page.locator('#cancellation-details').getAttribute('open'),null);
 assert.equal(await page.locator('#visits a[href="https://blog.ktz.me/the-yellowstone-geyser-basins/"]').count(),1);
 assert.equal(await page.locator('#notes img').count(),0);
 assert.ok((await page.locator('#visits').innerText()).length<1100,'Visits should stay concise');
 await checkAssociations();record('Associations are ordinary prose and one inline external link immediately after Visits');
 await imageReady(page.locator('.locator-map'));
 await page.evaluate(()=>scrollTo(0,0));
 const fonts=await page.evaluate(()=>({body:getComputedStyle(document.body).fontFamily,heading:getComputedStyle(document.querySelector('h1')).fontFamily,directory:getComputedStyle(document.querySelector('.directory')).fontFamily}));
 assert.match(fonts.body,/sans-serif/i);assert.match(fonts.heading,/serif/i);assert.doesNotMatch(fonts.heading,/sans-serif/i);assert.match(fonts.directory,/Inter/);record('classic article type, Inter directory, primary and secondary cancellations, inline visits and map',{fonts});
 await noOverflow();await page.screenshot({path:path.join(out,'desktop-place.png'),fullPage:true});await axe('desktop accessibility');
 await page.locator('#visits').evaluate(section=>section.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(out,'desktop-associations.png')});
 // Album links reveal the detail record without creating a separate journal page.
 const slot=page.locator('.cancellation-slot').first();const target=await slot.getAttribute('href');assert.ok(target?.startsWith('#cancellation-'));
 await slot.click();assert.equal(new URL(page.url()).hash,target);await expectOpen('#cancellation-details');assert.ok(await page.locator(target).isVisible());record('cancellation slot opens its record',{target});
 for(const anchor of ['#stamp-geyser-main','#visit-2019-06-19-1-stamp-1']){await page.goto(`${base}/places/yellowstone-national-park/${anchor}`);await expectOpen('#cancellation-details');assert.ok(await page.locator('#stamp-geyser-main').isVisible())}record('saved impression and legacy anchors reveal their details');
 // Opening a deep link also reveals its collapsed ancestors.
 await page.goto(`${base}/places/yellowstone-national-park/#location-centre-a`);await expectOpen('#stamping-locations');assert.ok(await page.locator('#location-centre-a').isVisible());
 const history=page.locator('.report-history').first();await history.locator('summary').click();assert.equal(await history.getAttribute('open'),'');assert.ok(await history.getByText('Imported listing',{exact:false}).isVisible());
 await page.screenshot({path:path.join(out,'desktop-locations.png'),fullPage:true});record('location anchor and report history disclosure');
 await page.locator('#location-centre-a').getByRole('link',{name:'June 19, 2019',exact:true}).click();assert.equal(new URL(page.url()).hash,'#visit-sample-visit');
 await page.locator('#visit-sample-visit').getByRole('link',{name:'USA road trip 2019 · sample',exact:true}).click();await page.waitForURL('**/trips/design-qa-trip/');assert.equal(await page.locator('.trip-stamp').count(),6);record('observation → inline visit → trip');
 await go('moores-creek-national-battlefield');assert.equal(await page.locator('.visit').count(),1);assert.equal(await page.locator('.cancellation-slot').count(),1);assert.equal(await page.locator('.cancellation-artwork').count(),1);assert.equal(await page.locator('.secondary-cancellations').count(),0);assert.equal(await page.locator('.primary-date time').getAttribute('datetime'),'2025-04-12');await imageReady(page.locator('.cancellation-artwork'));assert.equal(await page.locator('#visits a[href^="https://"]').count(),0);await imageReady(page.locator('.locator-map'));await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'desktop-one-stamp.png'),fullPage:true});await axe('one stamp accessibility');record('modest place, full primary impression and date, no required blog link');
 record('one primary plus 0–9 secondary square slots',{footprints:await verifyCountRange()});
 await page.screenshot({path:path.join(out,'desktop-ten-stamps.png'),fullPage:true});await go('qa-cancellation-count-9');await page.screenshot({path:path.join(out,'desktop-nine-stamps.png'),fullPage:true});
 await go('qa-cancellation-overflow');assert.equal(await page.locator('.cancellation-slot').count(),10);assert.equal(await page.locator('.secondary-cancellations .cancellation-slot').count(),9);assert.equal(await page.locator('.cancellation-summary').getAttribute('data-total'),'11');assert.equal(await page.locator('#cancellation-record-overflow-11').count(),1);await page.locator('.album-more a').click();await expectOpen('#cancellation-details');assert.ok(await page.locator('#cancellation-record-overflow-11').isVisible());await noOverflow();record('primary plus nine others, with overflow details retained');
 await go('qa-repeated-impression');assert.equal(await page.locator('.cancellation-slot').count(),1);assert.equal(await page.locator('.primary-slot').getAttribute('data-has-photo'),'true');assert.match(await page.locator('.primary-slot .cancellation-artwork').getAttribute('src'),/sample-stamp/);assert.equal(await page.locator('.primary-date time').getAttribute('datetime'),'2026-05-01');assert.equal(await page.locator('.primary-date time .sr-only').innerText(),'May 1, 2026');await page.locator('.primary-slot').click();await expectOpen('#cancellation-details');assert.ok(await page.locator('#stamp-first-impression').isVisible());assert.ok(await page.locator('#stamp-second-impression').isVisible());record('repeated primary uses latest collection date and older available photo, with both records retained');
 await go('qa-primary-uncollected');assert.equal(await page.locator('.primary-slot').getAttribute('href'),'#cancellation-record-primary');assert.equal(await page.locator('.primary-slot').getAttribute('data-collected'),'false');assert.equal(await page.locator('.primary-slot .cancellation-artwork').count(),0);assert.equal(await page.locator('.primary-slot .slot-placeholder').count(),1);assert.equal(await page.locator('.primary-date').count(),0);assert.match(await page.locator('.primary-slot').innerText(),/Not collected/);assert.equal(await page.locator('.secondary-cancellations .cancellation-artwork').count(),1);squareSlots(await albumGeometry());await noOverflow();await page.screenshot({path:path.join(out,'desktop-primary-uncollected.png'),fullPage:true});await axe('uncollected primary accessibility');record('uncollected first YAML cancellation stays primary');
 await go('qa-primary-photo-needed');assert.equal(await page.locator('.primary-slot').getAttribute('href'),'#cancellation-record-primary');assert.equal(await page.locator('.primary-slot').getAttribute('data-collected'),'true');assert.equal(await page.locator('.primary-slot').getAttribute('data-has-photo'),'false');assert.equal(await page.locator('.primary-slot .cancellation-artwork').count(),0);assert.match(await page.locator('.primary-slot .slot-placeholder').innerText(),/Photo needed/);assert.equal(await page.locator('.primary-date time').getAttribute('datetime'),'2026-09-19');assert.equal(await page.locator('.secondary-cancellations .cancellation-artwork').count(),1);squareSlots(await albumGeometry());await noOverflow();await page.screenshot({path:path.join(out,'desktop-primary-photo-needed.png'),fullPage:true});record('primary without photo keeps its own date and never borrows secondary artwork');
 await go('qa-legacy-album');assert.equal(await page.locator('.cancellation-slot').count(),2);await noOverflow();record('legacy collection without expected list');
 await go('qa-empty-album');assert.equal(await page.locator('.cancellation-slot').count(),0);await noOverflow();record('empty expected list creates no invented slots');
 await page.goto(base+'/regions/rocky-mountain/');await page.locator('#collection-filter').selectOption('collected');assert.equal(await page.locator('.album-slot:visible').count(),1);await page.locator('#collection-filter').selectOption('missing');assert.ok(await page.locator('.album-slot:visible').count()>1);record('region filters');await squareGallery();await page.screenshot({path:path.join(out,'desktop-region.png'),fullPage:true});await axe('region accessibility');
 // A state is its own visual collection, including shared places only once.
 await page.goto(base+'/regions/southeast/');await page.locator('main a[href="/states/georgia/"]').click();await page.waitForURL('**/states/georgia/');assert.equal(await page.locator('h1').innerText(),'Georgia');
 const georgia=expectedStatePlaces('GA');assert.equal(georgia.length,11);assert.deepEqual((await page.locator('main .album-slot').evaluateAll(cards=>cards.map(card=>card.getAttribute('href')))).sort(),georgia);
 assert.equal(await page.locator('main .album-slot img').count(),2);assert.equal(await page.locator('main .album-slot .empty-stamp').count(),9);for(const image of await page.locator('main .album-slot img').all())await imageReady(image);
 assert.equal(await page.locator('main .album-slot[href="/places/moores-creek-national-battlefield/"]').count(),0);assert.equal(await page.locator('main .album-slot[href="/places/yellowstone-national-park/"]').count(),0);
 assert.equal(await page.locator('.tree-state > .tree-row > a').evaluateAll(links=>links.every(link=>link.getAttribute('href').startsWith('/states/'))),true);assert.ok(await page.locator('.tree-state > .tree-row > a[href="/states/georgia/"][aria-current="page"]').count()>0);
 await page.locator('#collection-filter').selectOption('collected');assert.equal(await page.locator('.album-slot:visible').count(),2);await page.locator('#collection-filter').selectOption('missing');assert.equal(await page.locator('.album-slot:visible').count(),9);await page.locator('#collection-filter').selectOption('all');assert.equal(await page.locator('.album-slot:visible').count(),11);await noOverflow();await page.evaluate(()=>scrollTo(0,0));await squareGallery();await page.screenshot({path:path.join(out,'desktop-state-georgia.png'),fullPage:true});await axe('Georgia state accessibility');record('region → Georgia visual collection, exact state membership and gallery filters',{places:georgia});
 await page.goto(base+'/regions/southeast/');await page.locator('.tree-state > .tree-row > a[href="/states/georgia/"]:visible').click();await page.waitForURL('**/states/georgia/');record('Places state link opens the state collection');
 for(const state of ['wyoming','montana']){await page.goto(`${base}/states/${state}/`);const yellowstone=page.locator('main .album-slot[href="/places/yellowstone-national-park/"]');assert.equal(await yellowstone.count(),1);await yellowstone.click();await page.waitForURL('**/places/yellowstone-national-park/')}record('Wyoming and Montana share one canonical Yellowstone page');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/states/georgia/');await noOverflow();assert.deepEqual((await page.locator('main .album-slot').evaluateAll(cards=>cards.map(card=>card.getAttribute('href')))).sort(),georgia);for(const image of await page.locator('main .album-slot img').all())await imageReady(image);await page.evaluate(()=>scrollTo(0,0));await squareGallery();await page.screenshot({path:path.join(out,'mobile-state-georgia.png'),fullPage:true});await axe('Georgia mobile accessibility');await page.setViewportSize({width:1440,height:1100});
 await page.goto(base+'/search/?q=Ehrlich');await page.waitForFunction(()=>document.querySelector('#search-status').textContent.includes('result'));const associationResult=page.locator('#search-results a[href="/places/yellowstone-national-park/#associations"]');assert.equal(await associationResult.count(),1);await associationResult.click();await page.waitForURL('**/places/yellowstone-national-park/#associations');await checkAssociations();record('Association prose search links to the inline section');
 await page.goto(base+'/search/?q=wildlife');await page.waitForFunction(()=>document.querySelector('#search-status').textContent.includes('result'));assert.ok(await page.locator('#search-results li').count()>0);record('visit and stamp search');await axe('search accessibility');
 await go('yellowstone-national-park');
 if(await page.locator('.directory-toggle').getAttribute('aria-expanded')==='true')await page.getByRole('button',{name:'Hide places',exact:true}).click();
 const hiddenWidth=(await page.locator('main').boundingBox()).width;await page.getByRole('button',{name:'Browse places',exact:true}).click();assert.equal(await page.locator('.directory-toggle').getAttribute('aria-expanded'),'true');const shownWidth=(await page.locator('main').boundingBox()).width;assert.ok(hiddenWidth>shownWidth);
 await page.locator('#tree-filter').fill('Yellowstone');assert.equal(await page.locator('.tree-site:visible').count(),3);await page.locator('#tree-filter').fill('not-a-park');assert.ok(await page.locator('.tree-empty').isVisible());await page.locator('#tree-filter').fill('');await page.keyboard.press('Escape');assert.equal(await page.locator('.directory-toggle').getAttribute('aria-expanded'),'false');assert.ok(await page.locator('.directory-toggle').evaluate(e=>e===document.activeElement));record('collapsible place browser, filter, Escape and focus');
 await go('yellowstone-national-park');await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').textContent(),'Skip to content');assert.notEqual(await page.locator(':focus').evaluate(e=>getComputedStyle(e).outlineStyle),'none');await page.keyboard.press('Enter');assert.equal(new URL(page.url()).hash,'#content');record('keyboard skip link and focus');
 for(const width of [1920,1440,1280,1279,1024,768,390,320]){
  await page.setViewportSize({width,height:width<500?844:1100});await go('yellowstone-national-park');record('viewport '+width,await noOverflow());squareSlots(await albumGeometry());assert.equal(await page.locator('#stamping-locations').getAttribute('open'),null);assert.equal(await page.locator('.directory-toggle').getAttribute('aria-expanded'),String(width>=1280));
  await checkAssociations();
  if(width<=720){const order=await page.locator('#stamps,#cancellation-details,#stamping-locations,#visits,#associations,#notes,#park-facts').evaluateAll(sections=>sections.map(section=>section.id));assert.deepEqual(order,['stamps','cancellation-details','stamping-locations','visits','associations','notes','park-facts']);const positions=await page.locator('#visits,#associations,#notes').evaluateAll(sections=>Object.fromEntries(sections.map(section=>{const rect=section.getBoundingClientRect();return [section.id,{top:rect.top,bottom:rect.bottom}]})));assert.ok(positions.associations.top>=positions.visits.bottom-1,JSON.stringify(positions));assert.ok(positions.notes.top>=positions.associations.bottom-1,JSON.stringify(positions));record(`mobile reading and visual order at ${width}px`,{order,positions})}
  if([1024,390,320].includes(width)){await page.screenshot({path:path.join(out,`${width===1024?'tablet':width===390?'mobile':'small-mobile'}-place.png`),fullPage:true});if(width===390)await axe('mobile accessibility')}
  if([1920,1280,1279].includes(width))await page.screenshot({path:path.join(out,`${width===1920?'wide-desktop':width===1280?'small-desktop':'collapsed-desktop'}-place.png`),fullPage:true});
  if(width===390){await page.locator('#visits').evaluate(section=>section.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(out,'mobile-associations.png')});await page.getByRole('button',{name:'Browse places',exact:true}).click();assert.equal(await page.locator('.directory-toggle').getAttribute('aria-expanded'),'true');await page.locator('#tree-filter').fill('Yellowstone');assert.equal(await page.locator('.tree-site:visible').count(),3);await page.keyboard.press('Escape');assert.equal(await page.locator('.directory-toggle').getAttribute('aria-expanded'),'false');record('mobile directory')}
  await go('qa-long-name');await noOverflow();squareSlots(await albumGeometry());await page.locator('.cancellation-slot').first().click();await expectOpen('#cancellation-details');await noOverflow();for(const image of await page.locator('#cancellation-details img').all())await imageReady(image);const aspect=await page.locator('#cancellation-details img').evaluateAll(images=>images.map(i=>{const r=i.getBoundingClientRect();return {w:r.width,h:r.height,nw:i.naturalWidth,nh:i.naturalHeight,fit:getComputedStyle(i).objectFit}}));assert.equal(aspect.length,2);for(const i of aspect)assert.ok(i.fit==='contain'||Math.abs(i.w/i.h-i.nw/i.nh)<0.02,JSON.stringify(i));await imageReady(page.locator('.locator-map'));
  if(width!==1440)record(`primary and secondary counts at ${width}px`,{footprints:await verifyCountRange()});
 }
 await page.setViewportSize({width:720,height:550});await go('yellowstone-national-park');await noOverflow();record('200% desktop reflow equivalent');
 await page.setViewportSize({width:1440,height:1100});await page.goto(realBase+'/places/yellowstone-national-park/');assert.equal(await page.locator('.stamp').count(),0);assert.equal(await page.locator('.visit').count(),0);assert.equal(await page.locator('.cancellation-slot').count(),0);assert.equal(await page.locator('.location').count(),0);await page.screenshot({path:path.join(out,'desktop-blank.png'),fullPage:true});record('real vault remains blank');await axe('blank accessibility');
 const accessibilityFailures=results.filter(result=>result.violations?.length).map(result=>({name:result.name,violations:result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))}));assert.deepEqual(accessibilityFailures,[]);assert.deepEqual(errors,[]);record('browser errors',{errors});
 console.log(JSON.stringify({passed:true,results},null,2));
}finally{fs.writeFileSync(path.resolve('.qa/browser-results.json'),JSON.stringify({results,errors},null,2));await browser.close()}
