import {escape as e,slug,regions,stateNames} from './content.mjs';
const date=d=>new Intl.DateTimeFormat('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const external=(url,label)=>`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a>`;
const section=(title,body,id='')=>`<section ${id?`id="${id}"`:''}><h2>${e(title)}</h2>${body}</section>`;
const stamps=p=>p.data.visits.flatMap(v=>v.stamps);
const mains=p=>stamps(p).filter(s=>s.type==='main');
const collected=p=>mains(p).length>0;
export function createSite(model,catalogue,assetVersion) {
 const {nodes,places,trips,regionPages}=model;
 const regionURL=name=>regionPages.find(r=>r.title===name).url;
 function tree(current) {
  return regions.map(region=>{
   const members=places.filter(p=>p.data.passport_region===region);
   const states=[...new Set(members.flatMap(p=>p.data.states))].sort((a,b)=>stateNames[a].localeCompare(stateNames[b]));
   const open=current?.data.passport_region===region||current?.title===region;
   return `<details class="tree-region" data-label="${e(region)}" ${open?'open':''}><summary><a href="${regionURL(region)}">${e(region)}</a></summary>${states.map(state=>`<details class="tree-state" data-label="${e(stateNames[state])}" ${current?.data.states?.includes(state)?'open':''}><summary><a href="${regionURL(region)}#state-${state.toLowerCase()}">${e(stateNames[state])}</a></summary><div class="tree-sites">${members.filter(p=>p.data.states.includes(state)).map(p=>`<a class="tree-site" href="${p.url}" ${p===current?'aria-current="page"':''}>${e(p.title)}</a>`).join('')}</div></details>`).join('')}</details>`;
  }).join('');
 }
 function layout(title,body,current) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#ffffff"><meta name="description" content="${e(title)} — places, visits and collected stamps."><title>${e(title)} · The Stamp Book</title><link rel="stylesheet" href="/site.css?v=${assetVersion}"><script src="/app.js?v=${assetVersion}" defer></script></head><body><a class="skip-link" href="#content">Skip to content</a><header><a class="brand" href="/">The Stamp Book</a><form action="/search/" role="search"><label class="sr-only" for="header-search">Search the collection</label><input id="header-search" name="q" type="search" placeholder="Search places, visits, trips…"><button>Search</button></form></header><nav class="top-nav" aria-label="Main"><a href="/">Regions</a><a href="/places/">All places</a><a href="/trips/">Trips</a><a href="/about/">About</a></nav><div class="layout"><aside class="directory" aria-label="Place directory"><div class="directory-heading"><span>PLACES</span><button class="directory-toggle" aria-expanded="false" aria-controls="directory-content">Browse places</button></div><div id="directory-content"><label class="sr-only" for="tree-filter">Filter directory</label><input id="tree-filter" type="search" placeholder="Filter places…"><nav class="place-tree" aria-label="Regions, states and places">${tree(current)}</nav><p class="tree-empty" hidden>No matching places.</p></div></aside><main id="content">${body}</main></div><footer>The Stamp Book · Personal collection · <a href="/about/">Sources</a></footer></body></html>`;
 }
 const title=(name,kicker='')=>`${kicker?`<p class="kicker">${e(kicker)}</p>`:''}<h1>${e(name)}</h1>`;
 const backlinks=n=>n.backlinks.length?section('Linked from',`<ul>${n.backlinks.map(b=>`<li><a href="${b.url}">${e(b.title)}</a></li>`).join('')}</ul>`):'';
 function resources(p) {
  const links=catalogue.find(c=>c.code===p.data.park_code)?.resources||{};
  const labels={website:'Park website',maps:'Park maps',visit:'Plan your visit'};
  const official=Object.entries(links).filter(([k,url])=>labels[k]&&/^https:\/\/(www\.|home\.)?nps\.gov\//.test(url));
  return official.length?section('Official NPS resources',`<ul class="resource-links">${official.map(([k,url])=>`<li>${external(url,labels[k])}</li>`).join('')}</ul>`):'';
 }
 const stampCard=s=>`<article class="stamp" id="${s.anchor}"><div class="stamp-images">${s.images.length?s.images.map((src,i)=>`<a href="${src}" target="_blank" rel="noopener"><img src="${src}" alt="${e(s.name)}${s.images.length>1?' — photo '+(i+1):''}" loading="lazy"></a>`).join(''):'<div class="photo-pending">Collected · No photo</div>'}</div><p class="kicker">${s.type==='main'?'Main stamp':'Substamp'}</p><h3>${e(s.name)}</h3>${s.location?`<p>${e(s.location)}</p>`:''}<div class="prose">${s.html}</div><a class="small" href="${s.place.url}#${s.visit.anchor}">${date(s.date)}</a></article>`;
 function place(p) {
  const count=stamps(p).length;
  const info=`<aside class="infobox"><h2>Place details</h2><dl><dt>Region</dt><dd><a href="${regionURL(p.data.passport_region)}">${e(p.data.passport_region)}</a></dd><dt>States</dt><dd>${p.data.states.map(s=>e(stateNames[s])).join(', ')}</dd><dt>Stamps</dt><dd>${mains(p).length} main · ${count-mains(p).length} sub</dd></dl><h3>Visit history</h3>${p.data.visits.length?`<ol>${p.data.visits.map(v=>`<li><a href="#${v.anchor}">${date(v.date)}</a></li>`).join('')}</ol>`:'<p>No visits recorded.</p>'}</aside>`;
  return layout(p.title,`<nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Regions</a> / <a href="${regionURL(p.data.passport_region)}">${e(p.data.passport_region)}</a></nav>${title(p.title)}<div class="overview">${info}<div class="prose">${p.html||'<p class="muted">No place notes yet.</p>'}</div></div>${resources(p)}${section('Stamps',count?`<div class="stamp-grid">${stamps(p).map(stampCard).join('')}</div>`:'<p class="muted">No stamps recorded.</p>','stamps')}${section('Visits',p.data.visits.length?p.data.visits.map(v=>`<article class="visit" id="${v.anchor}"><h3>${date(v.date)}</h3>${v.trip?`<p class="trip-link"><a href="${nodes.find(n=>n.key===v.trip.slice(2,-2)).url}">${e(nodes.find(n=>n.key===v.trip.slice(2,-2)).title)}</a></p>`:''}<div class="prose">${v.html}</div>${v.stamps.length?`<ul>${v.stamps.map(s=>`<li><a href="#${s.anchor}">${e(s.name)}</a> <span class="small">${s.type==='main'?'Main stamp':'Substamp'}</span></li>`).join('')}</ul>`:''}</article>`).join(''):'<p class="muted">No visits recorded.</p>','visits')}${backlinks(p)}`,p);
 }
 function region(r) {
  const members=places.filter(p=>p.data.passport_region===r.title);
  const states=[...new Set(members.flatMap(p=>p.data.states))].sort((a,b)=>stateNames[a].localeCompare(stateNames[b]));
  return layout(r.title,`${title(r.title,'REGIONAL COLLECTION')}<div class="prose">${r.html}</div>${r.map?`<figure class="regional-map"><a href="${r.map}" target="_blank" rel="noopener"><img src="${r.map}" alt="${e(r.title)} regional book map"></a></figure>`:'<p class="muted">Regional book map not added.</p>'}<p>${external('https://www.nps.gov/subjects/gisandmapping/nps-maps.htm','Official NPS map library')}</p><p class="summary"><strong>${members.filter(collected).length} / ${members.length}</strong> places with a main stamp</p><div class="collection-controls"><label>Show <select id="collection-filter"><option value="all">All places</option><option value="collected">Main stamp recorded</option><option value="missing">No main stamp recorded</option></select></label></div><div class="album-grid">${members.map(p=>{const main=mains(p),image=main.flatMap(s=>s.images)[0];return `<a href="${p.url}" class="album-slot" data-collected="${main.length>0}">${image?`<img src="${image}" alt="${e(p.title)} main stamp" loading="lazy">`:`<span class="empty-stamp">${main.length?'Collected · No photo':'Not collected'}</span>`}<strong>${e(p.title)}</strong><span>${p.data.states.map(e).join(' · ')}</span>${main.length?`<span>${main.length} main ${main.length===1?'impression':'impressions'}</span>`:''}</a>`}).join('')}</div><p id="collection-empty" class="muted" hidden>No places match this filter.</p>${section('Places by state',`<div class="state-list">${states.map(s=>`<section id="state-${s.toLowerCase()}"><h3>${e(stateNames[s])}</h3><ul>${members.filter(p=>p.data.states.includes(s)).map(p=>`<li><a href="${p.url}">${e(p.title)}</a></li>`).join('')}</ul></section>`).join('')}</div>`)}${backlinks(r)}`,r);
 }
 function trip(t) {
  const visits=places.flatMap(p=>p.data.visits.filter(v=>v.trip===`[[${t.key}]]`).map(v=>({p,v}))).sort((a,b)=>a.v.date.localeCompare(b.v.date)||a.p.title.localeCompare(b.p.title));
  return layout(t.title,`${title(t.title,'TRIP')}<div class="prose">${t.html}</div><p class="summary">${visits.length} ${visits.length===1?'visit':'visits'} · ${visits.reduce((n,{v})=>n+v.stamps.length,0)} stamps</p>${visits.length?visits.map(({p,v})=>`<section><p class="kicker">${date(v.date)}</p><h2><a href="${p.url}#${v.anchor}">${e(p.title)}</a></h2><div class="prose">${v.html}</div>${v.stamps.length?`<div class="stamp-grid">${v.stamps.map(s=>`<a class="trip-stamp" href="${p.url}#${s.anchor}">${s.images[0]?`<img src="${s.images[0]}" alt="${e(s.name)}" loading="lazy">`:'<span class="empty-stamp">Collected · No photo</span>'}<strong>${e(s.name)}</strong><span>${s.type==='main'?'Main stamp':'Substamp'}</span></a>`).join('')}</div>`:''}</section>`).join(''):'<p class="muted">No visits linked to this trip.</p>'}${backlinks(t)}`,t);
 }
 const pages=new Map();
 pages.set('/',layout('Regions',`${title('The collection')}<p class="summary">${places.length} places · ${places.reduce((n,p)=>n+p.data.visits.length,0)} visits · ${places.reduce((n,p)=>n+stamps(p).length,0)} stamps</p><div class="region-grid">${regionPages.map(r=>{const members=places.filter(p=>p.data.passport_region===r.title);return `<a href="${r.url}"><h2>${e(r.title)}</h2><p>${members.filter(collected).length} / ${members.length} places with a main stamp</p></a>`}).join('')}</div>`));
 pages.set('/places/',layout('All places',`${title('All places')}<p>${places.length} places. <a href="/search/">Search the collection</a>.</p><ul class="all-places">${places.map(p=>`<li><a href="${p.url}">${e(p.title)}</a><span>${p.data.states.map(e).join(' · ')}</span></li>`).join('')}</ul>`));
 pages.set('/trips/',layout('Trips',`${title('Trips')}${trips.length?`<ul class="trip-list">${trips.map(t=>`<li><a href="${t.url}">${e(t.title)}</a></li>`).join('')}</ul>`:'<p class="muted">No trips recorded.</p>'}`));
 pages.set('/search/',layout('Search',`${title('Search')}<form id="search-form" action="/search/"><label for="search-input">Places, states, visits, stamps and trips</label><input id="search-input" type="search" name="q" autocomplete="off"><button>Search</button></form><p id="search-status" aria-live="polite"></p><ul id="search-results"></ul><noscript>Search requires JavaScript. <a href="/places/">Browse all places</a>.</noscript>`));
 pages.set('/about/',layout('About',`${title('About')}<p>A personal record of park visits and collected stamps.</p><p>Each place has one page, including places that span multiple states. Main stamps fill the regional collection; substamps stay with the place. A filled slot records a collection, not completion of every available stamp.</p>${section('Sources',`<p>The starting catalogue contains ${places.length} places imported from the original <a href="https://us-stamps.ktz.me/">US Stamps site</a>. It includes affiliated sites and separately listed park and preserve units.</p><ul><li>${external('https://www.nps.gov/','National Park Service')}</li><li>${external('https://www.nps.gov/subjects/gisandmapping/nps-maps.htm','Official NPS maps')}</li><li>${external('https://americasnationalparks.org/passport-to-your-national-parks/passport-cancellation-locations/','Passport cancellation locations')}</li></ul><p>Passport book regions are separate from NPS administrative regions. The initial state-based grouping can be adjusted in each place note.</p>`)}`));
 for(const n of nodes)pages.set(n.url,n.kind==='Places'?place(n):n.kind==='Regions'?region(n):trip(n));
 pages.set('/404.html',layout('Page not found',`${title('Page not found')}<p><a href="/search/">Search the collection</a> or <a href="/">browse regions</a>.</p>`));
 const search=nodes.map(n=>({title:n.title,url:n.url,kind:n.kind,text:[n.title,n.body,...(n.data.states||[]).flatMap(s=>[s,stateNames[s]]),n.data.passport_region||''].join(' ')}));
 for(const p of places)for(const v of p.data.visits){search.push({title:`${p.title} — ${v.date}`,kind:'Visit',url:p.url+'#'+v.anchor,text:`${p.title} ${v.date} ${v.notes||''} ${v.trip||''}`});for(const s of v.stamps)search.push({title:s.name,kind:s.type==='main'?'Main stamp':'Substamp',url:p.url+'#'+s.anchor,text:`${s.name} ${s.location||''} ${s.notes||''} ${v.date} ${p.title}`})}
 return {pages,search};
}
