import {stampTable} from './stamp-table.js';
import {Editor} from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import Image from '@tiptap/extension-image';
import Placeholder from '@tiptap/extension-placeholder';
const app=document.querySelector('#editor-app');
let key=app.dataset.key, csrf='', record, rendered={}, catalogue, dirty=false, editors=[], tab='edit', fresh=false, initializing=false, editSummary='', uploading=0;
const uid=()=>crypto.randomUUID?.()||'entry-'+Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,'0')).join('');
const el=(tag,attrs={},...children)=>{const n=document.createElement(tag);for(const [k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else if(k==='text')n.textContent=v;else if(v!==undefined&&v!==false)n.setAttribute(k,v===true?'':v)}for(const c of children.flat())if(c!==null&&c!==undefined)n.append(c instanceof Node?c:document.createTextNode(String(c)));return n};
const button=(text,action,cls='')=>el('button',{type:'button',class:cls,onclick:async e=>{try{await action(e)}catch(error){status(error.message,true)}}},text);
function status(message,error=false){let s=document.querySelector('#status');if(!s){s=el('div',{id:'status',role:'status'});app.prepend(s)}s.className='status'+(error?' error':'');s.textContent=message}
async function api(url,options={}){const h={'X-Stamp-Book-Version':app.dataset.version,'X-CSRF-Token':csrf,...options.headers};if(options.body&&!(options.body instanceof Blob)){h['Content-Type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(url,{...options,headers:h});noticeUpdate(r.headers.get('X-Stamp-Book-Version'));const data=await r.json().catch(()=>({error:`Request failed (${r.status})`}));if(!r.ok){const e=Error(data.error||data.message||`Request failed (${r.status})`);e.status=r.status;throw e}return data}
function draftKey(){return 'stamp-book-draft:'+key}
function change(){if(initializing||!record)return;dirty=true;try{localStorage.setItem(draftKey(),JSON.stringify({record,savedAt:new Date().toISOString()}))}catch{status('Your browser could not store a recovery draft. Keep this tab open until you save.',true)}}
function field(label,value,set,type='text',extra={}){const input=el(type==='textarea'?'textarea':'input',{'aria-label':label,type:type==='textarea'?undefined:type,value:type==='textarea'?undefined:value??'',...extra});if(type==='textarea')input.value=value??'';input.addEventListener('input',()=>{set(input.value);change()});return el('label',{},label,input)}
function select(label,value,options,set){const input=el('select',{'aria-label':label});for(const [v,t]of options)input.append(el('option',{value:v,selected:v===value},t));input.value=value??'';input.addEventListener('change',()=>{set(input.value);change()});return el('label',{},label,input)}
function removeFrom(list,item){if(confirm('Remove this entry from the draft? You can recover saved entries through History.')){list.splice(list.indexOf(item),1);change();showEditor()}}
function cleanEditors(){for(const e of editors)e.destroy();editors=[]}
function rich(label,doc,fallback,set){const wrapper=el('div',{class:'rich-wrap'}),host=el('div'),toolbar=el('div',{class:'toolbar',role:'toolbar','aria-label':label+' formatting'});wrapper.append(toolbar,host);const editor=new Editor({element:host,extensions:[StarterKit.configure({heading:{levels:[2,3]},link:{openOnClick:false,defaultProtocol:'https'}}),Image,Placeholder.configure({placeholder:label==='Associations'?'Books, music and other things connected to this place…':'Write a short entry…'})],content:doc?.json||doc?.html||fallback||'',editorProps:{attributes:{'aria-label':label,role:'textbox','aria-multiline':'true'}},onUpdate:({editor})=>{set({json:editor.getJSON(),html:editor.getHTML()});change()}});editors.push(editor);set({json:editor.getJSON(),html:editor.getHTML()});
 const cmds=[['Bold','bold',()=>editor.chain().focus().toggleBold().run()],['Italic','italic',()=>editor.chain().focus().toggleItalic().run()],['Heading','heading',()=>editor.chain().focus().toggleHeading({level:3}).run()],['Bullets','bulletList',()=>editor.chain().focus().toggleBulletList().run()],['Numbered','orderedList',()=>editor.chain().focus().toggleOrderedList().run()],['Link','link',()=>linkDialog(editor)],['Undo',null,()=>editor.chain().focus().undo().run()],['Redo',null,()=>editor.chain().focus().redo().run()]];
 for(const [name,active,cmd]of cmds){const b=button(name,cmd);if(active){b.setAttribute('aria-pressed',String(editor.isActive(active)));editor.on('transaction',()=>b.setAttribute('aria-pressed',String(editor.isActive(active))))}toolbar.append(b)}
 return el('div',{},el('p',{class:'hint'},label),wrapper)}
function linkDialog(editor){const dialog=el('dialog',{class:'link-dialog'}),input=el('input',{type:'url',value:editor.getAttributes('link').href||'',placeholder:'https://…'});dialog.append(el('label',{},'Link address',input),button('Apply link',()=>{const value=input.value.trim();if(value&&!/^(https?:\/\/|mailto:|\/|#)/i.test(value))throw Error('Use an https:// address, email link, or a site path.');if(value)editor.chain().focus().extendMarkRange('link').setLink({href:value}).run();else editor.chain().focus().unsetLink().run();dialog.close();dialog.remove()},'primary'),button('Remove link',()=>{editor.chain().focus().unsetLink().run();dialog.close();dialog.remove()}),button('Cancel',()=>{dialog.close();dialog.remove()}));document.body.append(dialog);dialog.showModal();input.focus()}
async function login(session){cleanEditors();app.replaceChildren();if(session.authMode==='oidc'){
 const panel=el('div',{class:'login'}),error=new URLSearchParams(location.search).get('authError');
 panel.append(el('h1',{},'Open Stampendium'),el('p',{},'Sign in to edit places, visits and cancellations.'));
 if(error)panel.append(el('p',{role:'alert'},error==='denied'?'Your account is not allowed to edit this book.':'Sign-in could not be completed. Please try again.'));
 panel.append(el('a',{class:'primary',href:'/auth/oidc/login?returnTo='+encodeURIComponent(location.pathname+location.search)},session.loginLabel));app.append(panel);return;
 }const form=el('form',{class:'login'}),password=el('input',{type:'password',autocomplete:'current-password',required:true});form.append(el('h1',{},'Open Stampendium'),el('p',{},'Sign in to edit places, visits and cancellations.'),el('label',{},'Editor password',password),el('button',{class:'primary',type:'submit'},'Sign in'));form.addEventListener('submit',async e=>{e.preventDefault();try{const r=await api('/api/login',{method:'POST',body:{password:password.value}});csrf=r.csrf||csrf;await start()}catch(error){status(error.message,true)}});app.append(form)}
async function start(){const session=await api('/api/session');csrf=session.csrf||'';if(!session.authenticated)return login(session);const logout=document.querySelector('#logout');logout.hidden=false;logout.onclick=async()=>{if(dirty&&!confirm('Sign out? Your unsaved recovery draft stays in this browser.'))return;await api('/api/logout',{method:'POST'});dirty=false;location.reload()};catalogue=await api('/api/catalogue');if(key){const result=await api('/api/records?key='+encodeURIComponent(key));record=result.record;rendered=result.rendered||{};showEditor();offerDraft();if(new URLSearchParams(location.search).get('view')==='history')await switchTab('history')}else if(['trip','place'].includes(new URLSearchParams(location.search).get('new'))){const kind=new URLSearchParams(location.search).get('new')==='place'?'Places':'Trips';key=kind+'/New '+(kind==='Trips'?'trip':'place');fresh=true;record={key,kind,revision:0,data:{title:'',...(kind==='Places'?{states:[],passport_region:'Southeast',visits:[],stamps:[]}: {})},body:'',prose:{}};rendered={};showEditor();offerDraft();app.querySelector('[aria-label="Title"]')?.focus()}else showCatalogue()}
function offerDraft(){let draft;try{draft=JSON.parse(localStorage.getItem(draftKey()))}catch{}if(!draft?.record)return;const notice=el('aside',{class:'draft-notice'},el('strong',{},'An unsaved draft is available'),el('p',{},`Saved on this device ${new Date(draft.savedAt).toLocaleString()}. ${draft.record.revision!==record.revision?'The published page has changed since this draft. Restoring it does not overwrite the newer page.':''}`),button('Restore draft',()=>{record=draft.record;dirty=true;showEditor();status('Draft restored. Review it before saving. Conflicting published changes will be protected.')}),button('Discard draft',()=>{localStorage.removeItem(draftKey());notice.remove()}));app.prepend(notice)}
function showCatalogue(){cleanEditors();app.replaceChildren(el('h1',{},'Edit Stampendium'),el('p',{},'Choose a page, or add a new place or trip.'));const search=el('input',{type:'search',placeholder:'Find a place, region or trip…','aria-label':'Find a page'}),list=el('ul',{class:'catalogue-list'});const paint=()=>{list.replaceChildren();for(const r of catalogue.records.filter(r=>(r.title+' '+r.kind).toLowerCase().includes(search.value.toLowerCase())).slice(0,100))list.append(el('li',{},el('a',{href:'/edit/?key='+encodeURIComponent(r.key)},r.title),el('small',{},r.kind)))};search.addEventListener('input',paint);app.append(el('p',{},el('a',{class:'primary new-trip-link',href:'/edit/?new=trip'},'Add trip')),search,list);paint();let kind='Trips',title='';const create=el('details',{class:'create-panel'},el('summary',{},'Create a place or trip'),select('Page type',kind,[['Trips','Trip'],['Places','Place']],v=>kind=v),field('Title','',v=>title=v),button('Create draft',()=>{if(!title.trim())throw Error('Give the page a title.');key=kind+'/'+title.trim();fresh=true;record={key,kind,revision:0,data:{title:title.trim(),...(kind==='Places'?{states:[],passport_region:'Southeast',visits:[],stamps:[]}: {})},body:'',prose:{}};rendered={};dirty=false;showEditor()},'primary'));app.append(create)}
function pagePicker(){
 const search=el('input',{type:'search',placeholder:'Find a place, region or trip…','aria-label':'Find a page'}),list=el('ul',{class:'catalogue-list',hidden:true});
 search.addEventListener('input',()=>{list.replaceChildren();list.hidden=!search.value.trim();if(list.hidden)return;for(const r of catalogue.records.filter(r=>(r.title+' '+r.kind).toLowerCase().includes(search.value.toLowerCase())).slice(0,20))list.append(el('li',{},el('a',{href:'/edit/?key='+encodeURIComponent(r.key)},r.title),el('small',{},r.kind)))});
 return el('div',{class:'page-picker'},el('label',{},'Find a page',search),list);
}
function showEditor(){const opened=new Set([...app.querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent.replace(/ · \d+$/,'')));cleanEditors();initializing=true;tab='edit';record.data??={};record.prose??={};app.replaceChildren(pagePicker(),el('a',{href:'/edit/'},'← All pages'),el('h1',{},record.data.title||(record.kind==='Trips'?'New trip':'New page')),el('p',{class:'muted'},`${record.kind} · ${fresh?'New draft':'Revision '+record.revision}`));const tabs=el('nav',{class:'editor-tabs','aria-label':'Page modes'}),panel=el('div',{id:'edit-panel'});for(const [id,label]of [['edit','Edit'],['preview','Preview'],['history','History']])tabs.append(button(label,()=>switchTab(id),id));app.append(tabs,el('div',{id:'status',role:'status'}),panel);renderForm(panel);for(const d of panel.querySelectorAll('details'))if(opened.has(d.querySelector('summary')?.textContent.replace(/ · \d+$/,'')))d.open=true;for(const b of tabs.children)b.setAttribute('aria-pressed',String(b.className==='edit'));initializing=false}
async function switchTab(mode){tab=mode;for(const b of document.querySelector('.editor-tabs').children)b.setAttribute('aria-pressed',String(b.className===mode));const panel=document.querySelector('#edit-panel');if(mode==='edit'){panel.hidden=false;document.querySelector('#other-panel')?.remove();return}panel.hidden=true;document.querySelector('#other-panel')?.remove();const other=el('div',{id:'other-panel'},'Loading…');app.append(other);if(mode==='preview'){const result=await api('/api/preview',{method:'POST',body:{record}});other.replaceChildren(el('p',{class:'hint'},'Preview of this draft. Nothing has been published.'),el('iframe',{class:'preview-frame',title:'Draft page preview',sandbox:'',srcdoc:result.html}));return}if(fresh){other.textContent='History starts when you save this page.';return}const data=await api('/api/history?key='+encodeURIComponent(key));other.replaceChildren(el('h2',{},'Revision history'),el('p',{},'Restoring creates a new revision. Earlier versions remain available.'));for(const rev of data.revisions)other.append(el('div',{class:'history-entry'},el('strong',{},'Revision '+rev.revision),el('p',{},`${new Date(rev.createdAt).toLocaleString()} · ${rev.actorName||rev.actor||"Unknown author"} · ${rev.summary||'No edit summary'}`),button('View this revision',async()=>{const result=await api('/api/revision?key='+encodeURIComponent(key)+'&revision='+rev.revision);const dialog=el('dialog',{class:'revision-dialog'},el('h2',{},'Revision '+rev.revision),button('Close revision',()=>{dialog.close();dialog.remove()}),el('iframe',{class:'preview-frame',title:'Saved revision preview',sandbox:'',srcdoc:result.html}));document.body.append(dialog);dialog.showModal()}),button('Restore this revision',async()=>{if(!confirm(`Restore revision ${rev.revision}? ${dirty?'Your unsaved draft will remain available in this browser. ':''}This creates a new saved revision.`))return;const result=await api('/api/restore?key='+encodeURIComponent(key),{method:'POST',body:{revision:rev.revision,expectedRevision:record.revision,summary:'Restored revision '+rev.revision}});record=result.record||(await api('/api/records?key='+encodeURIComponent(key))).record;const loaded=await api('/api/records?key='+encodeURIComponent(key));record=loaded.record;rendered=loaded.rendered||{};dirty=false;showEditor();status('Revision restored.');offerDraft()})))}
function renderForm(panel){const data=record.data;panel.append(el('a',{class:'save-jump',href:'#save-actions'},'Jump to save ↓'));if(record.kind!=='Places')panel.append(field('Title',data.title,v=>data.title=v,'text',{required:true}));if(record.kind==='Places'){const fields=el('div',{class:'fields'},field('Title',data.title,v=>data.title=v,'text',{required:true}),select('Passport region',data.passport_region,(catalogue.regions||[]).map(r=>[typeof r==='string'?r:r.title,typeof r==='string'?r:r.title]),v=>data.passport_region=v),field('Park code',data.park_code,v=>data.park_code=v));const states=el('div',{class:'state-picker',role:'group','aria-label':'States and territories'});for(const [code,name]of Object.entries(catalogue.states||{})){const input=el('input',{type:'checkbox',checked:(data.states||[]).includes(code)});input.addEventListener('change',()=>{data.states??=[];data.states=input.checked?[...data.states,code]:data.states.filter(s=>s!==code);change()});states.append(el('label',{},input,name))}fields.append(el('div',{class:'wide'},el('p',{},'States and territories'),states),field('Area (with units)',data.area,v=>{if(v)data.area=v;else delete data.area}),field('Established',data.established,v=>{if(v)data.established=v;else delete data.established},'date'));renderVisits(panel);panel.append(el('details',{class:'editor-fold',open:fresh},el('summary',{},'Place details & about'),fields,rich('About this place',record.prose.about,rendered.about,v=>record.prose.about=v),...(data.fact_sources||[]).map(source=>el('p',{class:'hint'},el('a',{href:source.url,target:'_blank',rel:'noopener'},source.label)))))}
 if(record.kind==='Trips')panel.append(field('Start date (optional)',data.start_date,v=>{if(v)data.start_date=v;else delete data.start_date},'date'),el('p',{class:'hint'},'Used to sort trips. If blank, the earliest linked visit supplies the date.'));if(record.kind!=='Places')panel.append(rich('Page text',record.prose.about,rendered.about,v=>record.prose.about=v));if(record.kind==='Places'){panel.append(el('details',{class:'editor-fold'},el('summary',{},'Associations'),rich('Associations',record.prose.associations,rendered.associations,v=>record.prose.associations=v)));renderExpected(panel);renderLocations(panel)}const actions=el('div',{class:'editor-actions',id:'save-actions'},field('Edit summary',editSummary,v=>editSummary=v,'text',{placeholder:'What changed?'}),button('Preview',()=>switchTab('preview')),button('Save changes',async e=>{const saveButton=e.currentTarget;saveButton.disabled=true;status('Saving changes…');try{for(const input of app.querySelectorAll('input[type=date]')){if(input.validity.badInput||(input.value&&Number(input.value.slice(0,4))<1000)){input.focus();throw Error('Enter a complete four-digit year for '+(input.getAttribute('aria-label')||'the date')+'.');}}const recoveryKey=draftKey();if(fresh){const title=record.data.title?.trim();if(!title)throw Error('Give the page a title.');record.data.title=title;record.key=record.kind+'/'+title;}if(uploading)throw Error('Wait for the photographs to finish uploading before saving.');const result=await api(fresh?'/api/records':'/api/records?key='+encodeURIComponent(key),{method:fresh?'POST':'PUT',body:{record,expectedRevision:record.revision,summary:editSummary}});dirty=false;editSummary='';localStorage.removeItem(recoveryKey);fresh=false;location.assign(result.url||catalogue.records.find(r=>r.key===key)?.url||'/');}catch(error){if(error.status===409)status('This page was changed after you opened it. Your draft is safe on this device. Open the published page in another tab to compare, then reload to load the newer revision. Restoring this draft retains its original revision so it cannot silently overwrite those changes.',true);else status(error.message,true)}finally{saveButton.disabled=false}},'primary'));panel.append(actions)}
function tableFor(visit,rows){return stampTable({data:record.data,visit,rows,el,button,change,refresh:showEditor,uid,photoEditor});}
function renderExpected(panel){const data=record.data;const linked=new Set(data.visits.flatMap(v=>v.stamps.map(s=>s.cancellation_id)));const rows=(data.stamps||[]).filter(s=>!linked.has(s.id)&&!data.visits.some(v=>v.stamps.some(c=>c.name===s.name&&c.type===s.type)));panel.append(el('details',{class:'editor-fold'},el('summary',{},`Other known stamps · ${rows.length}`),el('p',{class:'hint'},'Stamps you know about but have not collected. Just a name is enough. Collected stamps live in their visit tables.'),tableFor(null,rows)));}
function photoEditor(stamp){const dialog=el('dialog',{class:'photo-dialog'});const paint=()=>{dialog.replaceChildren(el('h2',{},stamp.name||'Stamp photos'),el('p',{class:'hint'},'A photo is optional. Record the actual collection date in the table.'),button('Done',()=>{dialog.close();dialog.remove();showEditor()}));renderPhotos(dialog,stamp,paint)};paint();document.body.append(dialog);dialog.showModal();dialog.addEventListener('cancel',()=>{dialog.remove();showEditor()});}
function uploadNewCancellations(visit){
 const input=el('input',{type:'file',accept:'image/jpeg,image/png,image/webp,image/gif',multiple:true,'aria-label':visit?'Upload stamps for this visit':'Upload stamps to create cancellations'});
 input.addEventListener('change',async()=>{
  const files=[...input.files];if(!files.length)return;input.disabled=true;uploading++;
  let target=visit,added=0,error;
  try{for(const file of files){
   const result=await api('/api/uploads?filename='+encodeURIComponent(file.name),{method:'POST',body:file,headers:{'Content-Type':file.type||'application/octet-stream'}});
   if(!target){target={id:uid(),date:'',notes:'',stamps:[]};record.data.visits.push(target)}
   target.stamps??=[];target.stamps.push({id:uid(),name:'',type:target.stamps.length?'sub':'main',photos:[result.ref]});added++;change();
  }}catch(e){error=e}finally{uploading--;showEditor();status(error?`${added} cancellation(s) added. ${error.message}`:`${added} cancellation(s) added. Enter each name and collected date, then save.`,!!error)}
 });
 return el('div',{class:'upload-new'},el('label',{},'Upload stamps — one cancellation per image',input),el('p',{class:'hint'},'Each image creates a row. Enter its name and collection date before saving.'));
}
function renderVisits(panel){const data=record.data;data.visits??=[];const section=el('section',{class:'editor-section visits-section'},el('div',{class:'entry-heading'},el('h2',{},'Visits & stamps'),button('Add visit',()=>{data.visits.push({id:uid(),date:'',notes:'',stamps:[]});change();showEditor()})),el('p',{class:'hint'},'One row per stamp. Photos are optional. Select Featured to choose the stamp shown first on the place page.'));data.visits.forEach((visit,i)=>{visit.stamps??=[];visit.id??=uid();const entry=el('section',{class:'visit-sheet','aria-label':`Visit ${i+1}`},el('div',{class:'visit-heading'},el('strong',{},`Visit ${i+1}`),field('Visit date',visit.date,v=>{visit.date=v;for(const input of entry.querySelectorAll('input[data-field="date"]')){const stamp=visit.stamps.find(s=>s.id===input.closest('tr').dataset.stampId);if(!stamp.date)input.value=v}},'date'),select('Trip',visit.trip||'',[['','No trip'],...catalogue.records.filter(r=>r.kind==='Trips').map(r=>[`[[${r.key}]]`,r.title])],v=>{if(v)visit.trip=v;else delete visit.trip}),button('Remove visit',()=>{const ids=new Set(visit.stamps.map(s=>s.id));if(confirm('Remove this visit from the draft? Saved versions remain in History.')){data.visits.splice(i,1);if(ids.has(data.featured_stamp_id))delete data.featured_stamp_id;change();showEditor()}},'danger')),tableFor(visit,visit.stamps),el('details',{class:'upload-fold'},el('summary',{},'Upload several stamp photos'),uploadNewCancellations(visit)),rich(`Visit ${i+1} notes`,visit.notes_doc,rendered.visits?.find(v=>v.index===i)?.html||visit.notes,v=>visit.notes_doc=v));section.append(entry)});if(!data.visits.length)section.append(el('p',{class:'hint'},'Add a visit to record its stamps and a short note.'));panel.append(section)}
function renderPhotos(parent,stamp,refresh=showEditor){stamp.photos??=[];const photos=el('div',{class:'photo-list'});for(const ref of stamp.photos){const path=ref.replace(/^\[\[/,'').replace(/\]\]$/,'').replace(/^Attachments\//,'/attachments/');photos.append(el('div',{class:'photo'},el('img',{src:path,alt:'Cancellation photograph'}),button('Remove photo',()=>{stamp.photos.splice(stamp.photos.indexOf(ref),1);change();refresh()})))}const upload=el('input',{type:'file',accept:'image/jpeg,image/png,image/webp,image/gif',multiple:true,'aria-label':'Upload cancellation photographs'});upload.addEventListener('change',async()=>{upload.disabled=true;uploading++;try{for(const file of upload.files){const result=await api('/api/uploads?filename='+encodeURIComponent(file.name),{method:'POST',body:file,headers:{'Content-Type':file.type||'application/octet-stream'}});stamp.photos.push(result.ref)}change();refresh();status('Photos uploaded. Save the page to attach them to this visit.')}catch(error){status(error.message,true)}finally{uploading--;upload.disabled=false}});parent.append(el('p',{class:'hint'},'Photographs · choose an image or use your phone camera'),photos,upload)}
const availability=['unknown','available','seasonal','unavailable','moved'].map(v=>[v,v[0].toUpperCase()+v.slice(1)]);
function renderLocations(panel){const data=record.data;data.stamping_locations??=[];const section=el('details',{class:'editor-fold'},el('summary',{},'Stamping locations'),el('p',{class:'hint'},'Optional. Existing reports are kept as a record; add a new observation when something changes.'));for(const location of data.stamping_locations){const entry=el('details',{class:'entry'},el('summary',{},location.name||'New stamping location'),el('div',{class:'fields'},field('Location name',location.name,v=>location.name=v),field('Map link',location.maps_url,v=>{if(v)location.maps_url=v;else delete location.maps_url},'url')));for(const report of location.reports||[])entry.append(el('div',{class:'report-history'},el('strong',{},report.availability),el('p',{},report.access||report.notes||'No access notes'),el('small',{},report.source?`${report.source.checked} · ${report.source.url}`:`Observation from visit ${data.visits.find(v=>v.id===report.visit_id)?.date||report.visit_id}`)));entry.append(button('Add new report',()=>reportForm(entry,location)));if(!location.reports?.length)entry.append(button('Remove empty location',()=>removeFrom(data.stamping_locations,location),'danger'));section.append(entry)}section.append(button('Add stamping location',()=>{const location={id:uid(),name:'New stamping location',reports:[]};data.stamping_locations.push(location);change();showEditor();const details=[...document.querySelectorAll('details.entry')].at(-1);details.open=true;reportForm(details,location)}));panel.append(section)}
function reportForm(parent,location){if(parent.querySelector('.new-report'))return;const data=record.data;let mode='source',visitId=data.visits.find(v=>v.id)?.id||'';const report={id:uid(),origin:'authored',availability:'unknown',access:'',stamps:[],source:{url:'',checked:new Date().toLocaleDateString('en-CA')}};const form=el('div',{class:'new-report'},el('h3',{},'New report'));const sourceFields=el('div',{class:'fields'},field('Source URL','',v=>report.source.url=v,'url'),field('Checked date',report.source.checked,v=>report.source.checked=v,'date'));const visitField=select('Observed during visit',visitId,data.visits.filter(v=>v.id).map(v=>[v.id,v.date]),v=>visitId=v);visitField.hidden=true;form.append(select('Report basis',mode,[['source','Published source'],['visit','My visit']],v=>{mode=v;sourceFields.hidden=v!=='source';visitField.hidden=v!=='visit'}),sourceFields,visitField,select('Availability',report.availability,availability,v=>report.availability=v),field('Access information','',v=>report.access=v,'textarea'),el('p',{class:'hint'},'Cancellations reported here'));for(const stamp of data.stamps||[]){const input=el('input',{type:'checkbox'});input.style.width='auto';input.addEventListener('change',()=>{report.stamps=input.checked?[...report.stamps,{name:stamp.name,type:stamp.type,availability:report.availability}]:report.stamps.filter(s=>s.name!==stamp.name)});form.append(el('label',{},input,' '+stamp.name))}form.append(button('Add report to draft',()=>{if(mode==='visit'){if(!visitId)throw Error('Add and date a visit before linking an observation.');delete report.source;report.visit_id=visitId}else if(!/^https?:\/\//.test(report.source.url)||!report.source.checked)throw Error('Enter a source URL and checked date.');location.reports??=[];location.reports.push(report);change();showEditor()}),button('Cancel report',()=>form.remove()));parent.append(form);parent.open=true}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
start().catch(error=>status(error.message,true));

function noticeUpdate(version){
 if(!version||version===app.dataset.version||document.querySelector('#app-update'))return;
 const notice=el('div',{id:'app-update',class:'status',role:'status'},'A new version is ready. Recovery drafts stay on this device. ',button('Reload to update',()=>location.reload()));
 document.querySelector('.editor-header').after(notice);
}
async function checkUpdate(){try{const response=await fetch('/healthz',{cache:'no-store'});noticeUpdate(response.headers.get('X-Stamp-Book-Version'))}catch{}}
setInterval(checkUpdate,60000);addEventListener('online',checkUpdate);
