import {parseStampRows,syncStampField} from './stamp-rows.mjs';
import {defaultFeaturedStamp} from '../src/cancellations.mjs';
export function stampTable({data,visit,rows,el,button,change,refresh,uid,photoEditor}){
 const chosen=data.featured_stamp_id||defaultFeaturedStamp(data),all=(data.visits||[]).flatMap(v=>v.stamps||[]),featuredId=(all.find(s=>s.id===chosen)||all.find(s=>s.cancellation_id===chosen))?.id||chosen;
 const known=!visit,wrap=el('div',{class:'stamp-sheet'}),toolbar=el('div',{class:'sheet-tools'}),selected=new Set();
 const announce=el('span',{class:'hint',role:'status'},`${rows.length} stamps`);
 const changed=()=>{change();announce.textContent=`${rows.length} stamps · changes not saved`};
 const sync=(stamp,field,value)=>{for(const linked of syncStampField(data,stamp,field,value)){for(const row of document.querySelectorAll('[data-stamp-id]'))if(row.dataset.stampId===linked.id){const input=row.querySelector(`[data-field="${field}"]`);if(input&&input!==document.activeElement)input.value=value}}changed()};
 const add=()=>{const stamp={id:uid(),name:'',type:rows.length?'sub':'main',...(known?{}:{photos:[]})};if(known){data.stamps??=[];data.stamps.push(stamp)}else rows.push(stamp);changed();refresh();requestAnimationFrame(()=>document.querySelector(`[data-stamp-id="${stamp.id}"] input[data-field="name"]`)?.focus())};
 const types=[['main','Main'],['sub','Additional'],['limited','Limited edition']];
 function control(stamp,field,type='text'){
  const label=`${field==='date'?'Collected date':field==='name'?'Stamp name':'Stamp type'} for row ${rows.indexOf(stamp)+1}`;
  const input=field==='type'?el('select',{'aria-label':label}):el('input',{type,'aria-label':label,value:stamp[field]??(field==='date'?visit?.date:'')??'',placeholder:field==='name'?'Stamp name':undefined});
  if(field==='type'){for(const [value,text]of types)input.append(el('option',{value},text));input.value=stamp.type||'main'}
  input.dataset.field=field;input.addEventListener(field==='type'?'change':'input',()=>{if(field==='date'){if(input.value){stamp.date=input.value;if(!visit.date){visit.date=input.value;input.closest('.visit-sheet').querySelector('input[aria-label="Visit date"]').value=input.value}}else delete stamp.date;changed()}else sync(stamp,field,input.value)});return input;
 }
 const table=el('table',{class:'stamp-table'}),head=el('tr');for(const title of ['Select','Stamp name','Type',...(known?[]:['Collected']), 'Photo','Featured',...(known?['Collect']:[])])head.append(el('th',{scope:'col'},title));const selectAll=el('input',{type:'checkbox','aria-label':'Select all stamp rows'});selectAll.onchange=()=>{for(const box of body.querySelectorAll('input[type=checkbox]')){box.checked=selectAll.checked;box.dispatchEvent(new Event('change'))}};head.firstChild.replaceChildren(selectAll);table.append(el('thead',{},head));const body=el('tbody');table.append(body);
 for(const stamp of rows){stamp.id??=uid();const row=el('tr',{'data-stamp-id':stamp.id});const pick=el('input',{type:'checkbox','aria-label':`Select stamp row ${rows.indexOf(stamp)+1}`});pick.onchange=()=>{pick.checked?selected.add(stamp):selected.delete(stamp);announce.textContent=`${selected.size} selected`};const feature=el('input',{type:'radio',name:'featured-stamp','aria-label':`Feature stamp row ${rows.indexOf(stamp)+1}${known?' from known stamps':''}`,checked:!!featuredId&&featuredId===stamp.id});feature.onchange=()=>{data.featured_stamp_id=stamp.id;changed()};
  const cell=el('div',{class:'cell-photo'});const photo=stamp.photos?.[0];const photos=button(photo?'Edit photo':'Add photo',()=>photoEditor(stamp),'photo-cell-button');photos.setAttribute('aria-label',`Photos for stamp row ${rows.indexOf(stamp)+1}`);if(photo)photos.prepend(el('img',{src:photo.replace(/^\[\[Attachments\//,'/attachments/').replace(/\]\]$/,''),alt:'',width:36,height:36}));cell.append(photos);
  row.append(el('td',{},pick),el('td',{},control(stamp,'name')),el('td',{},control(stamp,'type')));if(!known)row.append(el('td',{},control(stamp,'date','date')));row.append(el('td',{},cell),el('td',{},feature));if(known){const collect=el('select',{'aria-label':`Record ${stamp.name||'stamp'} in visit`});collect.append(el('option',{value:''},'Record in visit…'));for(const v of data.visits||[])collect.append(el('option',{value:v.id},v.date||'Undated visit'));collect.append(el('option',{value:'new'},'New visit…'));collect.onchange=()=>{if(!collect.value)return;let target=data.visits.find(v=>v.id===collect.value);if(!target){target={id:uid(),date:'',notes:'',stamps:[]};data.visits.push(target)}target.stamps.push({id:uid(),cancellation_id:stamp.id,name:stamp.name,type:stamp.type||'main',photos:[...(stamp.photos||[])]});changed();refresh()};row.append(el('td',{},collect))}body.append(row);
 }
 const remove=()=>{if(!selected.size)return;if(!confirm(`Remove ${selected.size} selected stamp${selected.size===1?'':'s'} from this draft?`))return;const list=known?data.stamps:rows;for(const stamp of selected){list.splice(list.indexOf(stamp),1);if(data.featured_stamp_id===stamp.id)delete data.featured_stamp_id}changed();refresh()};
 const bulk=el('select',{'aria-label':'Set type for selected stamps'});bulk.append(el('option',{value:''},'Set selected type…'));for(const [value,label]of types)bulk.append(el('option',{value},label));bulk.onchange=()=>{if(!bulk.value)return;for(const stamp of selected)sync(stamp,'type',bulk.value);refresh()};
 toolbar.append(button('Add row',add),button('Paste rows',()=>pasteDialog()),bulk,button('Remove selected',remove),announce);wrap.append(toolbar,el('div',{class:'table-scroll',tabindex:0,'aria-label':known?'Known stamps table':'Collected stamps table'},table));
 if(!rows.length)wrap.append(el('p',{class:'hint'},'Add a name to record a stamp. A photo is optional.'));
 function pasteDialog(){let parsed=[];const input=el('textarea',{'aria-label':'Stamp rows',placeholder:'Visitor centre\tMain\t2026-09-21\n250th anniversary\tLimited edition\t2026-09-21',rows:6}),message=el('p',{role:'status'});const dialog=el('dialog',{class:'paste-dialog'},el('h2',{},'Paste stamp rows'),el('p',{},known?'Paste tab-separated name and type columns.':'Paste tab-separated name, type, and optional collection date columns from a spreadsheet.'),input,message);dialog.append(button('Add rows',()=>{
  try{parsed=parseStampRows(input.value).map(s=>({id:uid(),...s,...(known?{date:undefined}:{})}))}catch(error){message.textContent=error.message;return}
  if(!input.value.trim())return;if(known){data.stamps??=[];data.stamps.push(...parsed)}else rows.push(...parsed);changed();dialog.close();dialog.remove();refresh();
 },'primary'),button('Cancel',()=>{dialog.close();dialog.remove()}));document.body.append(dialog);dialog.showModal();input.focus();}
 return wrap;
}
